#!/usr/bin/env python3
"""build_dropper.py — Generate a small shell dropper per action and hash it.

For each ActionSpec, write `files/<name>.sh` containing:

    #!/bin/bash
    cat "<target_path>" 2>&1
    echo "<dropper_name>"
    exit 0

Then compute SHA-256, SHA-1, MD5 and return them so the threat.yaml can embed
the hashes in `keyword_queries`.

Usage:
    python build_dropper.py --actions-json <in.json> --files-dir <out/files>

Prints a JSON map of {name: {path, sha256, sha1, md5}} to stdout.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import sys
import uuid
from pathlib import Path


DROPPER_TEMPLATE = """#!/bin/bash
# Auto-generated by picus-threat-yaml skill
# action:    {name}
# target:    {target_path}
# sha256:    {sha256}
cat "{target_path}" 2>&1
echo "{dropper_name}"
exit 0
"""


def _hashes(data: bytes) -> dict[str, str]:
    return {
        "sha256": hashlib.sha256(data).hexdigest(),
        "sha1":   hashlib.sha1(data).hexdigest(),
        "md5":    hashlib.md5(data).hexdigest(),
    }


def build_dropper(action: dict, files_dir: Path) -> dict:
    """Write a dropper for one action and return its hashes + path.

    Extension: `.bat` for Windows actions, `.sh` for Linux/others. Detected
    by the action's `shell_path` (Windows paths start with `C:\\` or contain
    `\\Windows\\`) or by an explicit `module` field on the action.
    """
    name = action["name"]
    target_path = action["target_path"]
    # Windows if the action names itself with a Windows path or the module
    # field says so.
    is_windows = (
        action.get("module") == "windows"
        or "\\" in action.get("shell_path", "")
        or action.get("os_name") == "Windows"
    )
    ext = ".bat" if is_windows else ".sh"
    dropper_name = f"{name}{ext}"

    # First pass: template without sha256 hash.
    body = DROPPER_TEMPLATE.format(
        name=name,
        target_path=target_path,
        sha256="(computed)",
        dropper_name=dropper_name,
    ).encode("utf-8")
    hashes = _hashes(body)

    # Second pass: write the body with the actual sha256 hash embedded.
    body = DROPPER_TEMPLATE.format(
        name=name,
        target_path=target_path,
        sha256=hashes["sha256"],
        dropper_name=dropper_name,
    ).encode("utf-8")
    # Re-hash to capture the final bytes (the embedded sha256 includes
    # itself — but this is the canonical pattern used in PUMAKIT).
    hashes = _hashes(body)

    # Picus stores a payload under a SINGLE base64 blob of
    # "<name>___<uuid><ext>" — the separator and extension are inside the
    # encoded string, and the padding is kept. Verified 76/76 against real
    # Picus exports.
    plain = f"{name}___{uuid.uuid4()}{ext}"
    archive_name = base64.b64encode(plain.encode("utf-8")).decode("ascii")

    # Where the dropper lands on the target, and what play_processes executes.
    drop_path = (f"%TEMP%\\{dropper_name}" if is_windows
                 else f"/tmp/{dropper_name}")

    files_dir.mkdir(parents=True, exist_ok=True)
    out_path = files_dir / archive_name
    out_path.write_bytes(body)
    out_path.chmod(0o755)

    return {
        "name": name,
        "dropper_name": dropper_name,
        "archive_name": archive_name,
        "drop_path": drop_path,
        "path": str(out_path),
        "sha256": hashes["sha256"],
        "sha1": hashes["sha1"],
        "md5": hashes["md5"],
    }


def main() -> None:
    p = argparse.ArgumentParser(description="Generate dropper scripts and embed hashes.")
    p.add_argument("--actions-json", required=True, type=Path)
    p.add_argument("--files-dir", required=True, type=Path)
    args = p.parse_args()

    actions = json.loads(args.actions_json.read_text(encoding="utf-8"))
    info: dict[str, dict] = {}
    for action in actions:
        result = build_dropper(action, args.files_dir)
        info[action["name"]] = result
    print(json.dumps(info, indent=2))


if __name__ == "__main__":
    main()
